" pathogen插件启动
execute pathogen#infect()
syntax on
syntax enable
filetype plugin indent on

""""""""""""""""""
"    基本配置    "
""""""""""""""""""

" 文件编码
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set backspace=2
set nowrap
set nocompatible

" 行号显示
set number

" tab键设置为空格
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" 特殊字符显示
set list
set listchars=tab:▸-,space:·

" 搜索高亮/增量/忽略大小写
set hlsearch
set incsearch
set ignorecase

" 高亮当前行
set cursorline
hi CursorColumn ctermbg=NONE ctermfg=yellow

" 相对行号
set relativenumber

" 状态栏
set laststatus=2
set statusline=
set statusline+=%f\ %r%m
set statusline+=%=
set statusline+=\ L\:%4l\/%-4L\ C\:%-3c
set statusline+=\ \[%{&fileformat}\]\ -
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}

""""""""""""""""
"   插件配置   "
""""""""""""""""

" nerdtree
let NERDTreeMinimalUI=1
let NERDChristmasTree=0
let NERDTreeIgnore=['\.swp$', '\.o$', '\.gcno$', '\.gcda$']
let NERDTreeWinPos='right'

" tagbar
let g:tagbar_left=1
let g:tagbar_width=35

" 
set updatetime=100

"
let g:interestingWordsTermColors = ['154', '121', '211', '137', '214', '222']
let g:rainbow_active = 1

" fzf.vim
let g:fzf_buffers_jump = 1
let g:fzf_preview_window = []
let g:fzf_layout = { 'down': '~20%' }
