" VundleVim 配置!!
" 中文真的大丈夫??
"===========!START!============
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'https://github.com/Lokaltog/vim-powerline'
call vundle#end()
filetype plugin indent on

"===========!END!==============
"
"配色
syntax on
set number
set fileencodings=ucs-bom,utf-8,utf-16,gbk,big5,gb18030,latin1

"PowerLine
set guifont=PowerlineSymbols/for/Powerline
set t_Co=256
let g:Powerline_symbols = 'fancy'
