#!/bin/python
import urllib.request
import json

url_api = 'http://api.wunderground.com/api/'
apikey = '/'
features = 'conditions/'
settings = '1/'
query= 'Asia/Chengdu.json'
url = url_api+apikey+features+settings+'q/'+query
#获取网页
html = urllib.request.urlopen(url)
#获取json表单
json_string = html.read()
parsed_json = json.loads(json_string)
#获取信息
temp_c = parsed_json['current_observation']['temp_c']
print(" ",temp_c,"°C")
html.close()
