#!/bin/python
import requests
import re
from bs4 import BeautifulSoup

url_seller='https://localbitcoins.com/zh-cn/buy-bitcoins-online/cny/'
content=requests.get(url_seller).content
soup=BeautifulSoup(content,'lxml')

price=soup.find_all(name='td',class_='column-price')
price_list=[]
pattern=re.compile('\d{1,10}\.\d{2}')
tot=0
cnt=0

for ad in price:
    result=pattern.findall(ad.string)
    result="".join(result)
    price_list.append(result)
    cnt=cnt+1
    tot=tot+float(result)

print(price_list)
