#!/bin/python
import os
import re

pattern_music=re.compile(r'^(.*)/(.*)\.(.*)')
pattern_time=re.compile(r'^(.*) (\d{1,3}:\d{1,2})')

command_info='mocp --info'

info=os.popen(command_info).readlines()

if(len(info) == 1):
    print('','无播放歌曲')
else:
    music=pattern_music.match(info[1]).group(2)
    lefttime=pattern_time.match(info[7]).group(2)
    tottime=pattern_time.match(info[6]).group(2)
    print('',music,lefttime+"/"+tottime)
